// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConfirmDialog(arg1:string,arg2:string):Promise<boolean>;

export function Exists(arg1:string):Promise<boolean>;

export function InstallCLI():Promise<string>;

export function IsCliInstalled():Promise<boolean>;

export function OpenFileDialog():Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function ReadDir(arg1:string):Promise<Array<main.FileEntry>>;

export function ReadTextFile(arg1:string):Promise<string>;

export function Remove(arg1:string):Promise<void>;

export function ShowMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function Stat(arg1:string):Promise<main.FileInfo>;

export function UninstallCLI():Promise<string>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
