// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmDialog(arg1, arg2) {
  return window['go']['main']['App']['ConfirmDialog'](arg1, arg2);
}

export function Exists(arg1) {
  return window['go']['main']['App']['Exists'](arg1);
}

export function InstallCLI() {
  return window['go']['main']['App']['InstallCLI']();
}

export function IsCliInstalled() {
  return window['go']['main']['App']['IsCliInstalled']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function Remove(arg1) {
  return window['go']['main']['App']['Remove'](arg1);
}

export function ShowMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowMessage'](arg1, arg2, arg3);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function Stat(arg1) {
  return window['go']['main']['App']['Stat'](arg1);
}

export function UninstallCLI() {
  return window['go']['main']['App']['UninstallCLI']();
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['main']['App']['WriteTextFile'](arg1, arg2);
}
